### ISSUE TITLE
Monthly Report Incorrect Format

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/github-contribution-report-generator#10]
The monthly report format does not match the required internal template.

**Comment by dabonnie** [comment]
This issue is mitigated by https://github.com/ros-tooling/github-contribution-report-generator/commit/f9e2a25af1e863d4fb206ab922ddb48785871f60. Programmatically generating the count removes the main pain point, while other internal modifications needed are relatively simple.

Thanks @thomas-moulard !

**Comment by thomas-moulard** [comment]
@dabonnie is this still needed?

**Comment by prajakta-gokhale** [comment]
No update, closing.
